import {
	REQUEST_FESTIVAL_SERIES,
	RECEIVE_FESTIVAL_SERIES,
	REQUEST_FESTIVAL_SERIES_CREATE,
	RECEIVE_FESTIVAL_SERIES_CREATE,
	REQUEST_FESTIVAL_SERIES_UPDATE,
	RECEIVE_FESTIVAL_SERIES_UPDATE,
	REQUEST_FESTIVAL_SERIES_DELETE,
	RECEIVE_FESTIVAL_SERIES_DELETE
} from '../utils/model-action-names.js';

const festivalSeries = (state = {}, action) => {

	switch (action.type) {

		case RECEIVE_FESTIVAL_SERIES:
		case RECEIVE_FESTIVAL_SERIES_CREATE:
		case RECEIVE_FESTIVAL_SERIES_UPDATE:
		case RECEIVE_FESTIVAL_SERIES_DELETE:
			return action.payload;

		case REQUEST_FESTIVAL_SERIES:
		case REQUEST_FESTIVAL_SERIES_CREATE:
		case REQUEST_FESTIVAL_SERIES_UPDATE:
		case REQUEST_FESTIVAL_SERIES_DELETE:
		default:
			return state;

	}

};

export default festivalSeries;
