const REQUEST_CHARACTER = 'REQUEST_CHARACTER';
const RECEIVE_CHARACTER = 'RECEIVE_CHARACTER';
const REQUEST_CHARACTER_TEMPLATE = 'REQUEST_CHARACTER_TEMPLATE';
const RECEIVE_CHARACTER_TEMPLATE = 'RECEIVE_CHARACTER_TEMPLATE';
const REQUEST_CHARACTER_CREATE = 'REQUEST_CHARACTER_CREATE';
const RECEIVE_CHARACTER_CREATE = 'RECEIVE_CHARACTER_CREATE';
const REQUEST_CHARACTER_UPDATE = 'REQUEST_CHARACTER_UPDATE';
const RECEIVE_CHARACTER_UPDATE = 'RECEIVE_CHARACTER_UPDATE';
const REQUEST_CHARACTERS = 'REQUEST_CHARACTERS';
const RECEIVE_CHARACTERS = 'RECEIVE_CHARACTERS';
const RECEIVE_NEW_FORM_DATA = 'RECEIVE_NEW_FORM_DATA';
const RECEIVE_EDIT_FORM_DATA = 'RECEIVE_EDIT_FORM_DATA';
const REQUEST_PERSON = 'REQUEST_PERSON';
const RECEIVE_PERSON = 'RECEIVE_PERSON';
const REQUEST_PERSON_TEMPLATE = 'REQUEST_PERSON_TEMPLATE';
const RECEIVE_PERSON_TEMPLATE = 'RECEIVE_PERSON_TEMPLATE';
const REQUEST_PERSON_CREATE = 'REQUEST_PERSON_CREATE';
const RECEIVE_PERSON_CREATE = 'RECEIVE_PERSON_CREATE';
const REQUEST_PERSON_UPDATE = 'REQUEST_PERSON_UPDATE';
const RECEIVE_PERSON_UPDATE = 'RECEIVE_PERSON_UPDATE';
const REQUEST_PEOPLE = 'REQUEST_PEOPLE';
const RECEIVE_PEOPLE = 'RECEIVE_PEOPLE';
const REQUEST_PLAYTEXT = 'REQUEST_PLAYTEXT';
const RECEIVE_PLAYTEXT = 'RECEIVE_PLAYTEXT';
const REQUEST_PLAYTEXT_TEMPLATE = 'REQUEST_PLAYTEXT_TEMPLATE';
const RECEIVE_PLAYTEXT_TEMPLATE = 'RECEIVE_PLAYTEXT_TEMPLATE';
const REQUEST_PLAYTEXT_CREATE = 'REQUEST_PLAYTEXT_CREATE';
const RECEIVE_PLAYTEXT_CREATE = 'RECEIVE_PLAYTEXT_CREATE';
const REQUEST_PLAYTEXT_UPDATE = 'REQUEST_PLAYTEXT_UPDATE';
const RECEIVE_PLAYTEXT_UPDATE = 'RECEIVE_PLAYTEXT_UPDATE';
const REQUEST_PLAYTEXTS = 'REQUEST_PLAYTEXTS';
const RECEIVE_PLAYTEXTS = 'RECEIVE_PLAYTEXTS';
const REQUEST_PRODUCTION = 'REQUEST_PRODUCTION';
const RECEIVE_PRODUCTION = 'RECEIVE_PRODUCTION';
const REQUEST_PRODUCTION_TEMPLATE = 'REQUEST_PRODUCTION_TEMPLATE';
const RECEIVE_PRODUCTION_TEMPLATE = 'RECEIVE_PRODUCTION_TEMPLATE';
const REQUEST_PRODUCTION_CREATE = 'REQUEST_PRODUCTION_CREATE';
const RECEIVE_PRODUCTION_CREATE = 'RECEIVE_PRODUCTION_CREATE';
const REQUEST_PRODUCTION_UPDATE = 'REQUEST_PRODUCTION_UPDATE';
const RECEIVE_PRODUCTION_UPDATE = 'RECEIVE_PRODUCTION_UPDATE';
const REQUEST_PRODUCTIONS = 'REQUEST_PRODUCTIONS';
const RECEIVE_PRODUCTIONS = 'RECEIVE_PRODUCTIONS';
const REQUEST_THEATRE = 'REQUEST_THEATRE';
const RECEIVE_THEATRE = 'RECEIVE_THEATRE';
const REQUEST_THEATRE_TEMPLATE = 'REQUEST_THEATRE_TEMPLATE';
const RECEIVE_THEATRE_TEMPLATE = 'RECEIVE_THEATRE_TEMPLATE';
const REQUEST_THEATRE_CREATE = 'REQUEST_THEATRE_CREATE';
const RECEIVE_THEATRE_CREATE = 'RECEIVE_THEATRE_CREATE';
const REQUEST_THEATRE_UPDATE = 'REQUEST_THEATRE_UPDATE';
const RECEIVE_THEATRE_UPDATE = 'RECEIVE_THEATRE_UPDATE';
const REQUEST_THEATRES = 'REQUEST_THEATRES';
const RECEIVE_THEATRES = 'RECEIVE_THEATRES';

export {
	REQUEST_CHARACTER,
	RECEIVE_CHARACTER,
	REQUEST_CHARACTER_TEMPLATE,
	RECEIVE_CHARACTER_TEMPLATE,
	REQUEST_CHARACTER_CREATE,
	RECEIVE_CHARACTER_CREATE,
	REQUEST_CHARACTER_UPDATE,
	RECEIVE_CHARACTER_UPDATE,
	REQUEST_CHARACTERS,
	RECEIVE_CHARACTERS,
	RECEIVE_NEW_FORM_DATA,
	RECEIVE_EDIT_FORM_DATA,
	REQUEST_PERSON,
	RECEIVE_PERSON,
	REQUEST_PERSON_TEMPLATE,
	RECEIVE_PERSON_TEMPLATE,
	REQUEST_PERSON_CREATE,
	RECEIVE_PERSON_CREATE,
	REQUEST_PERSON_UPDATE,
	RECEIVE_PERSON_UPDATE,
	REQUEST_PEOPLE,
	RECEIVE_PEOPLE,
	REQUEST_PLAYTEXT,
	RECEIVE_PLAYTEXT,
	REQUEST_PLAYTEXT_TEMPLATE,
	RECEIVE_PLAYTEXT_TEMPLATE,
	REQUEST_PLAYTEXT_CREATE,
	RECEIVE_PLAYTEXT_CREATE,
	REQUEST_PLAYTEXT_UPDATE,
	RECEIVE_PLAYTEXT_UPDATE,
	REQUEST_PLAYTEXTS,
	RECEIVE_PLAYTEXTS,
	REQUEST_PRODUCTION,
	RECEIVE_PRODUCTION,
	REQUEST_PRODUCTION_TEMPLATE,
	RECEIVE_PRODUCTION_TEMPLATE,
	REQUEST_PRODUCTION_CREATE,
	RECEIVE_PRODUCTION_CREATE,
	REQUEST_PRODUCTION_UPDATE,
	RECEIVE_PRODUCTION_UPDATE,
	REQUEST_PRODUCTIONS,
	RECEIVE_PRODUCTIONS,
	REQUEST_THEATRE,
	RECEIVE_THEATRE,
	REQUEST_THEATRE_TEMPLATE,
	RECEIVE_THEATRE_TEMPLATE,
	REQUEST_THEATRE_CREATE,
	RECEIVE_THEATRE_CREATE,
	REQUEST_THEATRE_UPDATE,
	RECEIVE_THEATRE_UPDATE,
	REQUEST_THEATRES,
	RECEIVE_THEATRES
};
